export const FIELD_DANH_SACH_XE_TAI_DANG_KY = {
  STT: 'STT',
  BIEN_SO_XE: 'licensePlate',
  MA_SO_XE: 'code',
  LOAI_XE: 'type',
  GROUP: 'group',
  CAN_XAC: 'weighingMethod',
  VI_TRI_CAN: 'weighingPosition',
  NGAY_TOI: 'arrivalDate',
  THOI_GIAN_TOI: 'arrivalTime',
  LOAI_DA: 'loaiDa',
  VI_TRI_LAY_DA: 'viTriLayDa',
  DOANH_THU: 'revenueType',
  CONG_TY_MUA: 'congTyMua',
  DIEM_DEN: 'diemDen',
  QUANG_DUONG: 'distance',
  EMAIL_CO_QUAN: 'email',
  DIEN_THOAI_CO_QUAN: 'dienThoaiCoQuan',
  DIA_CHI: 'address',
  THANH_PHO: 'thanhPho',
  MA_BUU_CHINH: 'maBuuChinh',
  MO_TA: 'description',
  NAME: 'name',
  KHO: 'destinationWarehouse',
  TO_KHO: 'toDestinationWarehouse',
};

export const FIELD_DAN_SACH_XE_TAI_ADD_NEW = {
  TRUCK_ID: 'truckId',
  TO_DATE: 'arrivalDate',
  FROM_TIME: 'fromArrivalTime',
  TO_TIME: 'arrivalTime',
  STONE_TYPE_ID: 'stoneTypeId',
  MACHINERIES_ID: 'pickupPositionId',
  REVENUE_TYPE: 'revenueType',
  BUYER_COMPANY_ID: 'buyerCompanyId',
  DEPLOY_POINT: 'destinationId',
  WAREHOUSES_ID: 'destinationWarehouseId',
  TO_WAREHOUSES_ID: 'toDestinationWarehouseId',
  TRIP_NUM: 'tripNumber',
  MO_TA: 'description',
};
