export const WEIGHT_METHOD_OPTIONS_VALUE = {
  CAN_MOI_DAU_NGAY: 'Cân Mõi Đầu Ngày',
  CAN_1_LAN: 'Cân 1 Lần',
  CAN_MOI_CHUYEN: 'Cân Mõi Chuyến',
};
export const WEIGHT_METHOD_OPTIONS = [
  {
    label: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_DAU_NGAY,
    value: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_DAU_NGAY,
  },
  {
    label: WEIGHT_METHOD_OPTIONS_VALUE.CAN_1_LAN,
    value: WEIGHT_METHOD_OPTIONS_VALUE.CAN_1_LAN,
  },
  {
    label: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_CHUYEN,
    value: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_CHUYEN,
  },
];
