export const WEIGHT_METHOD_OPTIONS_VALUE = {
  CAN_MOI_DAU_NGAY: 'Cân mỗi chuyến',
  CAN_1_LAN: 'Cân 1 lần',
  CAN_MOI_CHUYEN: 'Cân mỗi chuyến',
};
export const WEIGHT_METHOD_OPTIONS = [
  {
    label: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_DAU_NGAY,
    value: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_DAU_NGAY,
  },
  {
    label: WEIGHT_METHOD_OPTIONS_VALUE.CAN_1_LAN,
    value: WEIGHT_METHOD_OPTIONS_VALUE.CAN_1_LAN,
  },
  {
    label: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_CHUYEN,
    value: WEIGHT_METHOD_OPTIONS_VALUE.CAN_MOI_CHUYEN,
  },
];

export const WEIGHT_POSITION_OPTIONS_VALUE = {
  CAN_1: 'Cân 1',
  CAN_2: 'Cân 2',
  CAN_3: 'Cân 3',
};
export const WEIGHT_POSITION_OPTIONS = [
  {
    label: WEIGHT_POSITION_OPTIONS_VALUE.CAN_1,
    value: WEIGHT_POSITION_OPTIONS_VALUE.CAN_1,
  },
  {
    label: WEIGHT_POSITION_OPTIONS_VALUE.CAN_2,
    value: WEIGHT_POSITION_OPTIONS_VALUE.CAN_2,
  },
  {
    label: WEIGHT_POSITION_OPTIONS_VALUE.CAN_3,
    value: WEIGHT_POSITION_OPTIONS_VALUE.CAN_3,
  },
];
