export const ACTIVITIES_FIELD = {
  REGISTRATION_ID: 'registrationId',
  VI_TRI_CAN: 'viTriCan',
  LOAI_DA: 'stoneTypeId',
  VI_TRI_LAY_DA: 'stoneType',
  DOANH_THU: 'revenueType',
  CONG_TY_MUA: 'buyerCompany',
  THOI_GIAN_VAO_CONG: 'gateInTime',
  THOI_GIAN_CAN_LAN_1: 'weighTime1',
  VI_TRI_CAN_LAN_1: 'weighPosition1',
  KHOI_LUONG1: 'weight1',
  THOI_GIAN_CAN_LAN_2: 'weighTime2',
  VI_TRI_CAN_LAN_2: 'weighPosition2',
  KHOI_LUONG2: 'weight2',
  TRONG_LUONG_HANG: 'trongLuongHang',
  THOI_GIAN_RA_CONG: 'gateOutTime',
  GIO_VAO_CONG: 'gateTimeIn',
  GIO_RA_CONG: 'gateTimeOut',
};
